#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

source ${MYPATH}/env
source ${MYPATH}/vpr_common

parse_args $@ 

if [ -z $PCF ]; then
     echo "Please provide pcf file name"
     exit 1
fi

if [ -z $NET ]; then
     echo "Please provide net file name"
     exit 1
fi

OUT_NOISY_WARNINGS=noisy_warnings-${DEVICE}_place.log

echo "Generating constraints ..."
symbiflow_generate_constraints $EBLIF $NET $PART $DEVICE $ARCH_DEF $PCF

run_vpr --fix_clusters constraints.place --place --route

mv vpr_stdout.log place_n_route.log
